# Generated by Django 5.2.3 on 2025-07-01 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(limit_choices_to={'user_type': 'auditor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_account_name', models.CharField(help_text='kpay, wavepay,bank etc.. ဖွင့်ထားသောအမည်', max_length=100)),
                ('payment_account_type', models.CharField(help_text='payment account အမျိုးအစား(ဥပမာ- kpay, wavepay, bank etc..)', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='ငွေပေးချေမှုနေ့စွဲ')),
                ('transfer_id_last_6_digits', models.CharField(max_length=6, verbose_name='Transaction ID (နောက်ဆုံး ၆ လုံး)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ပမာဏ')),
                ('transaction_type', models.CharField(choices=[('receivable', 'ရရန်ရှိ'), ('payable', 'ပေးရန်ရှိ')], default='receivable', max_length=10, verbose_name='မှတ်တမ်းအမျိုးအစား')),
                ('image', models.ImageField(blank=True, null=True, upload_to='transaction_images/', verbose_name='ပုံ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='တင်ပြသည့်အချိန်')),
                ('status', models.CharField(choices=[('pending', 'စောင့်ဆိုင်းဆဲ'), ('approved', 'အတည်ပြုပြီး'), ('rejected', 'ပယ်ချပြီး')], default='pending', max_length=10, verbose_name='အခြေအနေ')),
                ('approved_by_owner_at', models.DateTimeField(blank=True, null=True, verbose_name='ပိုင်ရှင်မှအတည်ပြုသည့်အချိန်')),
                ('owner_notes', models.TextField(blank=True, null=True, verbose_name='ပိုင်ရှင်မှတ်ချက်')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.group', verbose_name='အဖွဲ့')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.paymentaccount', verbose_name='ငွေပေးချေမှုအကောင့်')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_transactions', to=settings.AUTH_USER_MODEL, verbose_name='တင်ပြသူ')),
            ],
            options={
                'verbose_name': 'ငွေပေးချေမှုမှတ်တမ်း',
                'verbose_name_plural': 'ငွေပေးချေမှုမှတ်တမ်းများ',
                'ordering': ['-submitted_at'],
                'unique_together': {('transfer_id_last_6_digits', 'payment_account')},
            },
        ),
    ]
