# Generated by Django 5.2.3 on 2025-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'ဝင်ငွေ'), ('expense', 'ထွက်ငွေ')], default='income', max_length=10, verbose_name='မှတ်တမ်းအမျိုးအစား'),
        ),
    ]
