# Generated by Django 5.2.3 on 2025-07-02 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Sheets ငွေပေးချေမှုမှတ်တမ်း', 'verbose_name_plural': 'Sheets ငွေပေးချေမှုမှတ်တမ်းများ'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sheets_transaction_images/', verbose_name='ပုံ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets_submitted_transactions', to=settings.AUTH_USER_MODEL, verbose_name='တင်ပြသူ'),
        ),
    ]
