# Generated by Django 5.2.3 on 2025-07-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_alter_transaction_options_alter_transaction_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'စာရင်းစစ်မှတ်တမ်း', 'verbose_name_plural': 'စာရင်းစစ်မှတ်တမ်းများ'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'အဖွဲ့', 'verbose_name_plural': 'အဖွဲ့များ'},
        ),
        migrations.AlterModelOptions(
            name='paymentaccount',
            options={'ordering': ['payment_account_name'], 'verbose_name': 'ငွေပေးချေမှုအကောင့်', 'verbose_name_plural': 'ငွေပေးချေမှုအကောင့်များ'},
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='auditor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'auditor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='စစ်ဆေးသူ'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ဖန်တီးသည့်အချိန်'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.group', verbose_name='အဖွဲ့'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='နောက်ဆုံးပြင်ဆင်သည့်အချိန်'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ပေးရန်ပမာဏ'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='receivable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ရရန်ပမာဏ'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='မှတ်ချက်'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ဖန်တီးသည့်အချိန်'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_title',
            field=models.CharField(max_length=255, verbose_name='အဖွဲ့ခေါင်းစဉ်'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(max_length=255, verbose_name='အဖွဲ့အမျိုးအစား'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='အမည်'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ပိုင်ရှင်'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='နောက်ဆုံးပြင်ဆင်သည့်အချိန်'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ဘဏ်အကောင့်နံပါတ်'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ဘဏ်အမည်'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ဖန်တီးသည့်အချိန်'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ပိုင်ရှင်'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='payment_account_name',
            field=models.CharField(help_text='kpay, wavepay,bank etc.. ဖွင့်ထားသောအမည်', max_length=100, verbose_name='အကောင့်အမည်'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='payment_account_type',
            field=models.CharField(help_text='payment account အမျိုးအစား(ဥပမာ- kpay, wavepay, bank etc..)', max_length=100, verbose_name='အကောင့်အမျိုးအစား'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ဖုန်းနံပါတ်'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='နောက်ဆုံးပြင်ဆင်သည့်အချိန်'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_images/', verbose_name='ပုံ'),
        ),
    ]
